[package]
name = "amdgpu_top"
description = "Tool to display AMDGPU usage"
version = "${PKG_VERSION}"
homepage = "https://github.com/Umio-Yasuno/amdgpu_top"
license = "MIT"
command = "bin/amdgpu_top"
working-dir = "inherit"

[bundle]
strip = true
scan-dlopen = true

[compression]
level = 22
